# Generated by Django 5.1.3 on 2024-11-10 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('group', models.CharField(choices=[('development', 'Development'), ('commercial', 'Commercial'), ('production', 'Production'), ('service', 'Service'), ('users', 'Users'), ('other', 'Other')], max_length=50)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('designer', 'Designer'), ('other', 'Other')], max_length=50)),
                ('licenselevel', models.CharField(blank=True, max_length=50)),
                ('employment_type', models.CharField(choices=[('MSD', 'MSD'), ('other', 'Other')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('ip_clearance_level', models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 3', 'Level 3')], max_length=50)),
                ('ip_clearance', models.CharField(blank=True, max_length=50)),
                ('catalog_task_id', models.CharField(blank=True, max_length=255)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
