# Generated by Django 5.1.3 on 2024-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_userdata_delete_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='catalog_tasks_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='employment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='group',
            field=models.CharField(choices=[('development', 'Development'), ('commercial', 'Commercial'), ('production', 'Production'), ('service', 'Service'), ('users', 'Users')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='license_level',
            field=models.CharField(default='consumer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Designer', 'Designer')], max_length=20),
        ),
    ]
