# Generated by Django 5.1.3 on 2024-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_userdata_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
